# Falcon Admission Installation.
#
# Example using all/many available options
---
apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconAdmission
metadata:
  labels:
    crowdstrike.com/component: sample
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: falcon-admission
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: falconadmission
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  name: falcon-admission
spec:
  installNamespace: falcon-kac
  falcon_api:
    client_id: PLEASE_FILL_IN
    client_secret: PLEASE_FILL_IN
    cloud_region: autodiscover
    # (optional, default is derived from the API Key pair)
    cid: 00001111222233334444555566667777-12
  falcon:
    apd: false
    aph: this.proxy.com
    app: 8080
    # (required when not using the API Key pair)
    cid: 00001111222233334444555566667777-12
    billing: metered
    trace: none
    tags:
      - admission_controller
      - tags1
      - tags2
  resourcequota:
    pods: "2"
  admissionConfig:
    replicas: 2
    serviceAccount:
      annotations:
        # These are just examples, you wouldn't combine AWS & GKE roles at once
        eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/iam-role-name
        iam.gke.io/gcp-service-account: $GCP_SERVICE_ACCOUNT@$GCP_PROJECT_ID.iam.gserviceaccount.com
        annotation2: annotation-value
    imagePullPolicy: Always
    imagePullSecrets:
      - name: your-pre-created-secret
      - name: your-pre-created-secret2
    servicePort: 443
    containerPort: 4443
    failurePolicy: Fail
    tls:
      validity: 123
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 50Mi
    resourcesClient:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 50Mi
    disabledNamespaces:
      namespaces:
        - test1
        - test2
        - test3
      # Use only on OpenShift to ignore OpenShift namespaces
      ignoreOpenShiftNamespaces: true
  registry:
    type: acr
    acr_name: falcon-sensor-repo
    tls:
      insecure_skip_verify: false
  # (required when not using the API Key pair)
  image: repo.host.com:4000/name:tag
  version: 1.2.3.tagname
